### ISSUE TITLE
Add const keyword on variable

### ISSUE THREAD

**Issue by ragasubekti** [dickymr/project-javascript-string-methods#1]
https://github.com/dickymr/project-javascript-string-methods/blob/2cc7c1e2a4d2df408fa872bb8df61da71d24c02f/index.js#L3-L4

**Comment by dickymr** [comment]
![oke-bro](https://user-images.githubusercontent.com/46373553/56020265-edbe5d00-5d30-11e9-9e9b-8e6f5ead5a65.jpg)

Done. Thanks
